import { PlatformPreset } from '../types/presets';

export const PLATFORM_PRESETS: PlatformPreset[] = [
  // --- TIKTOK ---
  {
    id: 'tiktok-9-16',
    platform: 'tiktok',
    label: 'Full Screen Feed',
    labelKey: 'ttFullScreen',
    category: 'vertical',
    aspectRatio: { w: 9, h: 16 },
    recommendedResolution: { w: 1080, h: 1920 },
    description: 'Standard 9:16 feed video & photo mode. Critical safe zones on right rail and bottom.',
    safeZones: [
      {
        id: 'tt-top',
        name: 'Top Header & Search',
        top: 0, left: 0, width: 100, height: 12,
        description: 'Search icon, Following / For You / LIVE tabs',
      },
      {
        id: 'tt-bottom',
        name: 'Caption & Sound Marquee',
        bottom: 0, left: 0, width: 82, height: 22,
        description: 'Account handle, multi-line caption, audio title, navigation bar',
      },
      {
        id: 'tt-right-rail',
        name: 'Interaction Rail',
        top: 42, right: 0, width: 18, height: 44,
        description: 'Avatar follow, Like, Comment, Bookmark, Share buttons, spinning audio disc',
      },
    ],
  },

  // --- INSTAGRAM ---
  {
    id: 'ig-reels-9-16',
    platform: 'instagram',
    label: 'Reels & Stories',
    labelKey: 'igReelsStories',
    category: 'vertical',
    aspectRatio: { w: 9, h: 16 },
    recommendedResolution: { w: 1080, h: 1920 },
    description: 'Full vertical screen with UI elements on top and bottom margins.',
    safeZones: [
      {
        id: 'ig-top',
        name: 'Stories / Reels Header',
        top: 0, left: 0, width: 100, height: 14,
        description: 'Profile picture, handle, elapsed story progress bars, close button',
      },
      {
        id: 'ig-bottom',
        name: 'Caption & Audio Info',
        bottom: 0, left: 0, width: 84, height: 22,
        description: 'Username, description text, audio link, sponsored CTA button',
      },
      {
        id: 'ig-right-rail',
        name: 'Action Rail',
        top: 48, right: 0, width: 18, height: 38,
        description: 'Like, Comment, Share, More options menu',
      },
    ],
  },
  {
    id: 'ig-feed-4-5',
    platform: 'instagram',
    label: 'Feed Portrait',
    labelKey: 'igFeedPortrait',
    category: 'portrait',
    aspectRatio: { w: 4, h: 5 },
    recommendedResolution: { w: 1080, h: 1350 },
    description: 'Most engaging Instagram feed ratio. Maximizes vertical screen real-estate without cropping.',
  },
  {
    id: 'ig-grid-3-4',
    platform: 'instagram',
    label: 'Profile Grid Tile',
    labelKey: 'igProfileGrid',
    category: 'portrait',
    aspectRatio: { w: 3, h: 4 },
    recommendedResolution: { w: 1080, h: 1440 },
    description: 'Latest Instagram profile grid aspect ratio. Keep key visuals centered to prevent header crop.',
  },
  {
    id: 'ig-feed-1-1',
    platform: 'instagram',
    label: 'Feed Square',
    labelKey: 'igFeedSquare',
    category: 'square',
    aspectRatio: { w: 1, h: 1 },
    recommendedResolution: { w: 1080, h: 1080 },
    description: 'Classic 1:1 square post. Matches profile grid preview directly.',
  },
  {
    id: 'ig-feed-16-9',
    platform: 'instagram',
    label: 'Feed Landscape',
    labelKey: 'igFeedLandscape',
    category: 'landscape',
    aspectRatio: { w: 16, h: 9 },
    recommendedResolution: { w: 1920, h: 1080 },
    description: 'Horizontal widescreen post on Instagram mobile and web feed.',
  },

  // --- X (TWITTER) ---
  {
    id: 'x-vertical-9-16',
    platform: 'x',
    label: 'Vertical Video (9:16)',
    labelKey: 'xVertical',
    category: 'vertical',
    aspectRatio: { w: 9, h: 16 },
    recommendedResolution: { w: 1080, h: 1920 },
    description: 'X Immersive full-screen vertical video player for mobile timeline.',
    safeZones: [
      {
        id: 'x-top',
        name: 'Player Top Bar',
        top: 0, left: 0, width: 100, height: 12,
        description: 'Back button, audio mute, overflow options',
      },
      {
        id: 'x-bottom',
        name: 'Account, Text & Scrubber',
        bottom: 0, left: 0, width: 82, height: 20,
        description: 'Handle, post text, time scrubber bar',
      },
      {
        id: 'x-right-rail',
        name: 'Engagement Rail',
        top: 48, right: 0, width: 18, height: 38,
        description: 'Like heart, Repost, Reply, Bookmark, Share',
      },
    ],
  },
  {
    id: 'x-portrait-4-5',
    platform: 'x',
    label: 'Expanded Portrait (4:5)',
    labelKey: 'xPortrait',
    category: 'portrait',
    aspectRatio: { w: 4, h: 5 },
    recommendedResolution: { w: 1440, h: 1800 },
    description: 'Newly supported official expanded vertical format for X feed media & ads.',
  },
  {
    id: 'x-feed-1-1',
    platform: 'x',
    label: 'Square Post (1:1)',
    labelKey: 'xSquare',
    category: 'square',
    aspectRatio: { w: 1, h: 1 },
    recommendedResolution: { w: 1080, h: 1080 },
    description: 'Square photo or video timeline post with maximal feed compactness.',
  },
  {
    id: 'x-feed-16-9',
    platform: 'x',
    label: 'Landscape Card (16:9)',
    labelKey: 'xLandscape',
    category: 'landscape',
    aspectRatio: { w: 16, h: 9 },
    recommendedResolution: { w: 1920, h: 1080 },
    description: 'Default widescreen video and link card preview aspect ratio.',
  },
  {
    id: 'x-landscape-191-1',
    platform: 'x',
    label: 'Web Link Card (1.91:1)',
    labelKey: 'xLinkCard',
    category: 'landscape',
    aspectRatio: { w: 1200, h: 628 },
    recommendedResolution: { w: 1200, h: 628 },
    description: 'Standard 1.91:1 banner card for web previews and sponsored ads.',
  },

  // --- YOUTUBE ---
  {
    id: 'yt-shorts-9-16',
    platform: 'youtube',
    label: 'Shorts',
    labelKey: 'ytShorts',
    category: 'vertical',
    aspectRatio: { w: 9, h: 16 },
    recommendedResolution: { w: 1080, h: 1920 },
    description: 'Mobile vertical feed video with like/comment rail on the right side.',
    safeZones: [
      {
        id: 'yt-top',
        name: 'Top Bar',
        top: 0, left: 0, width: 100, height: 10,
        description: 'Shorts logo, camera button, search, overflow menu',
      },
      {
        id: 'yt-bottom',
        name: 'Channel & Title',
        bottom: 0, left: 0, width: 82, height: 19,
        description: 'Channel avatar, name, red Subscribe button, sound track title',
      },
      {
        id: 'yt-right-rail',
        name: 'Action Icons',
        top: 46, right: 0, width: 18, height: 40,
        description: 'Thumbs up, Thumbs down, Comments, Share, Remix icons',
      },
    ],
  },
  {
    id: 'yt-video-16-9',
    platform: 'youtube',
    label: 'Video & Thumbnails',
    labelKey: 'ytVideo',
    category: 'landscape',
    aspectRatio: { w: 16, h: 9 },
    recommendedResolution: { w: 1920, h: 1080 },
    description: 'Standard widescreen 16:9 format for horizontal video, thumbnails, and desktop displays.',
  },

  // --- THREADS ---
  {
    id: 'threads-video-9-16',
    platform: 'threads',
    label: 'Vertical Video',
    labelKey: 'thVertical',
    category: 'vertical',
    aspectRatio: { w: 9, h: 16 },
    recommendedResolution: { w: 1080, h: 1920 },
    description: 'Full vertical mobile video (up to 5 mins). Fills screen vertically for peak engagement.',
    safeZones: [
      {
        id: 'threads-top',
        name: 'Author Header',
        top: 0, left: 0, width: 100, height: 10,
        description: 'Profile avatar, username, timestamp, and post menu',
      },
      {
        id: 'threads-bottom',
        name: 'Action Bar (Like, Reply, Repost)',
        bottom: 0, left: 0, width: 100, height: 13,
        description: 'Interaction buttons: heart, reply bubble, repost, share icon',
      },
    ],
  },
  {
    id: 'threads-feed-4-5',
    platform: 'threads',
    label: 'Feed Portrait',
    labelKey: 'thFeedPortrait',
    category: 'portrait',
    aspectRatio: { w: 4, h: 5 },
    recommendedResolution: { w: 1080, h: 1350 },
    description: 'The golden format for Threads feed photos and carousels. Maximizes screen real estate without feed cropping.',
  },
  {
    id: 'threads-feed-1-1',
    platform: 'threads',
    label: 'Feed Square',
    labelKey: 'thFeedSquare',
    category: 'square',
    aspectRatio: { w: 1, h: 1 },
    recommendedResolution: { w: 1080, h: 1080 },
    description: 'Standard 1:1 square post. Safely preserves full frame without crop in single posts and carousels.',
  },
  {
    id: 'threads-landscape-16-9',
    platform: 'threads',
    label: 'Landscape & Link Card',
    labelKey: 'thLandscape',
    category: 'landscape',
    aspectRatio: { w: 16, h: 9 },
    recommendedResolution: { w: 1920, h: 1080 },
    description: 'Horizontal widescreen captures, landscape video clips, and web link preview cards.',
  },

  // --- FACEBOOK ---
  {
    id: 'fb-stories-9-16',
    platform: 'facebook',
    label: 'Stories & Reels',
    labelKey: 'fbStoriesReels',
    category: 'vertical',
    aspectRatio: { w: 9, h: 16 },
    recommendedResolution: { w: 1080, h: 1920 },
    description: 'Full vertical screen with Facebook header and reaction bar.',
    safeZones: [
      {
        id: 'fb-top',
        name: 'Stories Bar',
        top: 0, left: 0, width: 100, height: 12,
        description: 'Story segment indicators, author profile, close button',
      },
      {
        id: 'fb-bottom',
        name: 'Reactions & Message Box',
        bottom: 0, left: 0, width: 100, height: 16,
        description: 'Quick emoji reactions bar and reply text box',
      },
    ],
  },
  {
    id: 'fb-feed-4-5',
    platform: 'facebook',
    label: 'Mobile Feed',
    labelKey: 'fbMobileFeed',
    category: 'portrait',
    aspectRatio: { w: 4, h: 5 },
    recommendedResolution: { w: 1080, h: 1350 },
    description: 'Highest converting aspect ratio for mobile Facebook feed ads and organic posts.',
  },
];
